# Generated by Django 4.0 on 2021-12-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineA',
            fields=[
                ('identity', models.AutoField(primary_key=True, serialize=False)),
                ('shift_model', models.IntegerField()),
                ('std_shift_time_gross', models.IntegerField()),
                ('start_up', models.IntegerField()),
                ('break_time', models.IntegerField()),
                ('lunch', models.IntegerField()),
                ('other', models.IntegerField()),
                ('std_shift_time', models.IntegerField(default=470)),
                ('days_or_week', models.IntegerField()),
                ('weeks_per_year', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='LineB',
            fields=[
                ('identity', models.AutoField(primary_key=True, serialize=False)),
                ('shift_model', models.IntegerField()),
                ('std_shift_time_gross', models.IntegerField()),
                ('start_up', models.IntegerField()),
                ('break_time', models.IntegerField()),
                ('lunch', models.IntegerField()),
                ('other', models.IntegerField()),
                ('std_shift_time', models.IntegerField(default=470)),
                ('days_or_week', models.IntegerField()),
                ('weeks_per_year', models.IntegerField(default=50)),
            ],
        ),
    ]
