# Generated by Django 4.0 on 2021-12-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='linea',
            name='std_shift_time',
        ),
        migrations.RemoveField(
            model_name='lineb',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='lineb',
            name='std_shift_time',
        ),
        migrations.AlterField(
            model_name='linea',
            name='shift_model',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lineb',
            name='shift_model',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
